<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "sakila_customer".
 *
 * @property integer $customer_id
 * @property integer $store_id
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property integer $address_id
 * @property integer $active
 * @property string $create_date
 * @property string $last_update
 *
 * @property \app\models\SakilaAddress $address
 * @property \app\models\SakilaStore $store
 * @property \app\models\SakilaPayment[] $sakilaPayments
 * @property \app\models\SakilaRental[] $sakilaRentals
 * @property string $aliasModel
 */
abstract class SakilaCustomer extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sakila_customer';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['store_id', 'first_name', 'last_name', 'address_id', 'create_date'], 'required'],
            [['store_id', 'address_id', 'active'], 'integer'],
            [['create_date', 'last_update'], 'safe'],
            [['first_name', 'last_name'], 'string', 'max' => 45],
            [['email'], 'string', 'max' => 50],
            [['address_id'], 'exist', 'skipOnError' => true, 'targetClass' => SakilaAddress::className(), 'targetAttribute' => ['address_id' => 'address_id']],
            [['store_id'], 'exist', 'skipOnError' => true, 'targetClass' => SakilaStore::className(), 'targetAttribute' => ['store_id' => 'store_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'customer_id' => Yii::t('app', 'Customer ID'),
            'store_id' => Yii::t('app', 'Store ID'),
            'first_name' => Yii::t('app', 'First Name'),
            'last_name' => Yii::t('app', 'Last Name'),
            'email' => Yii::t('app', 'Email'),
            'address_id' => Yii::t('app', 'Address ID'),
            'active' => Yii::t('app', 'Active'),
            'create_date' => Yii::t('app', 'Create Date'),
            'last_update' => Yii::t('app', 'Last Update'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAddress()
    {
        return $this->hasOne(\app\models\SakilaAddress::className(), ['address_id' => 'address_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStore()
    {
        return $this->hasOne(\app\models\SakilaStore::className(), ['store_id' => 'store_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSakilaPayments()
    {
        return $this->hasMany(\app\models\SakilaPayment::className(), ['customer_id' => 'customer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSakilaRentals()
    {
        return $this->hasMany(\app\models\SakilaRental::className(), ['customer_id' => 'customer_id']);
    }


    
    /**
     * @inheritdoc
     * @return SakilaCustomerQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\SakilaCustomerQuery(get_called_class());
    }


}
