<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "sakila_staff".
 *
 * @property integer $staff_id
 * @property string $first_name
 * @property string $last_name
 * @property integer $address_id
 * @property resource $picture
 * @property string $email
 * @property integer $store_id
 * @property integer $active
 * @property string $username
 * @property string $password
 * @property string $last_update
 *
 * @property \app\models\SakilaPayment[] $sakilaPayments
 * @property \app\models\SakilaRental[] $sakilaRentals
 * @property \app\models\SakilaAddress $address
 * @property \app\models\SakilaStore $store
 * @property \app\models\SakilaStore $sakilaStore
 * @property string $aliasModel
 */
abstract class SakilaStaff extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sakila_staff';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['first_name', 'last_name', 'address_id', 'store_id', 'username'], 'required'],
            [['address_id', 'store_id', 'active'], 'integer'],
            [['picture'], 'string'],
            [['last_update'], 'safe'],
            [['first_name', 'last_name'], 'string', 'max' => 45],
            [['email'], 'string', 'max' => 50],
            [['username'], 'string', 'max' => 16],
            [['password'], 'string', 'max' => 40],
            [['address_id'], 'exist', 'skipOnError' => true, 'targetClass' => SakilaAddress::className(), 'targetAttribute' => ['address_id' => 'address_id']],
            [['store_id'], 'exist', 'skipOnError' => true, 'targetClass' => SakilaStore::className(), 'targetAttribute' => ['store_id' => 'store_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'staff_id' => Yii::t('app', 'Staff ID'),
            'first_name' => Yii::t('app', 'First Name'),
            'last_name' => Yii::t('app', 'Last Name'),
            'address_id' => Yii::t('app', 'Address ID'),
            'picture' => Yii::t('app', 'Picture'),
            'email' => Yii::t('app', 'Email'),
            'store_id' => Yii::t('app', 'Store ID'),
            'active' => Yii::t('app', 'Active'),
            'username' => Yii::t('app', 'Username'),
            'password' => Yii::t('app', 'Password'),
            'last_update' => Yii::t('app', 'Last Update'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSakilaPayments()
    {
        return $this->hasMany(\app\models\SakilaPayment::className(), ['staff_id' => 'staff_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSakilaRentals()
    {
        return $this->hasMany(\app\models\SakilaRental::className(), ['staff_id' => 'staff_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAddress()
    {
        return $this->hasOne(\app\models\SakilaAddress::className(), ['address_id' => 'address_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStore()
    {
        return $this->hasOne(\app\models\SakilaStore::className(), ['store_id' => 'store_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSakilaStore()
    {
        return $this->hasOne(\app\models\SakilaStore::className(), ['manager_staff_id' => 'staff_id']);
    }


    
    /**
     * @inheritdoc
     * @return SakilaStaffQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\SakilaStaffQuery(get_called_class());
    }


}
