<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "sakila_language".
 *
 * @property integer $language_id
 * @property string $name
 * @property string $last_update
 *
 * @property \app\models\SakilaFilm[] $sakilaFilms
 * @property \app\models\SakilaFilm[] $sakilaFilms0
 * @property string $aliasModel
 */
abstract class SakilaLanguage extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sakila_language';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['last_update'], 'safe'],
            [['name'], 'string', 'max' => 20]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'language_id' => Yii::t('app', 'Language ID'),
            'name' => Yii::t('app', 'Name'),
            'last_update' => Yii::t('app', 'Last Update'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSakilaFilms()
    {
        return $this->hasMany(\app\models\SakilaFilm::className(), ['language_id' => 'language_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSakilaFilms0()
    {
        return $this->hasMany(\app\models\SakilaFilm::className(), ['original_language_id' => 'language_id']);
    }


    
    /**
     * @inheritdoc
     * @return SakilaLanguageQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\SakilaLanguageQuery(get_called_class());
    }


}
