<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "sakila_payment".
 *
 * @property integer $payment_id
 * @property integer $customer_id
 * @property integer $staff_id
 * @property integer $rental_id
 * @property string $amount
 * @property string $payment_date
 * @property string $last_update
 *
 * @property \app\models\SakilaCustomer $customer
 * @property \app\models\SakilaRental $rental
 * @property \app\models\SakilaStaff $staff
 * @property string $aliasModel
 */
abstract class SakilaPayment extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sakila_payment';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['customer_id', 'staff_id', 'amount', 'payment_date'], 'required'],
            [['customer_id', 'staff_id', 'rental_id'], 'integer'],
            [['amount'], 'number'],
            [['payment_date', 'last_update'], 'safe'],
            [['customer_id'], 'exist', 'skipOnError' => true, 'targetClass' => SakilaCustomer::className(), 'targetAttribute' => ['customer_id' => 'customer_id']],
            [['rental_id'], 'exist', 'skipOnError' => true, 'targetClass' => SakilaRental::className(), 'targetAttribute' => ['rental_id' => 'rental_id']],
            [['staff_id'], 'exist', 'skipOnError' => true, 'targetClass' => SakilaStaff::className(), 'targetAttribute' => ['staff_id' => 'staff_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'payment_id' => Yii::t('app', 'Payment ID'),
            'customer_id' => Yii::t('app', 'Customer ID'),
            'staff_id' => Yii::t('app', 'Staff ID'),
            'rental_id' => Yii::t('app', 'Rental ID'),
            'amount' => Yii::t('app', 'Amount'),
            'payment_date' => Yii::t('app', 'Payment Date'),
            'last_update' => Yii::t('app', 'Last Update'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(\app\models\SakilaCustomer::className(), ['customer_id' => 'customer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRental()
    {
        return $this->hasOne(\app\models\SakilaRental::className(), ['rental_id' => 'rental_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStaff()
    {
        return $this->hasOne(\app\models\SakilaStaff::className(), ['staff_id' => 'staff_id']);
    }


    
    /**
     * @inheritdoc
     * @return SakilaPaymentQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\SakilaPaymentQuery(get_called_class());
    }


}
