<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "sakila_inventory".
 *
 * @property integer $inventory_id
 * @property integer $film_id
 * @property integer $store_id
 * @property string $last_update
 *
 * @property \app\models\SakilaFilm $film
 * @property \app\models\SakilaStore $store
 * @property \app\models\SakilaRental[] $sakilaRentals
 * @property string $aliasModel
 */
abstract class SakilaInventory extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sakila_inventory';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['film_id', 'store_id'], 'required'],
            [['film_id', 'store_id'], 'integer'],
            [['last_update'], 'safe'],
            [['film_id'], 'exist', 'skipOnError' => true, 'targetClass' => SakilaFilm::className(), 'targetAttribute' => ['film_id' => 'film_id']],
            [['store_id'], 'exist', 'skipOnError' => true, 'targetClass' => SakilaStore::className(), 'targetAttribute' => ['store_id' => 'store_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'inventory_id' => Yii::t('app', 'Inventory ID'),
            'film_id' => Yii::t('app', 'Film ID'),
            'store_id' => Yii::t('app', 'Store ID'),
            'last_update' => Yii::t('app', 'Last Update'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFilm()
    {
        return $this->hasOne(\app\models\SakilaFilm::className(), ['film_id' => 'film_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStore()
    {
        return $this->hasOne(\app\models\SakilaStore::className(), ['store_id' => 'store_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSakilaRentals()
    {
        return $this->hasMany(\app\models\SakilaRental::className(), ['inventory_id' => 'inventory_id']);
    }


    
    /**
     * @inheritdoc
     * @return SakilaInventoryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\SakilaInventoryQuery(get_called_class());
    }


}
