<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "sakila_store".
 *
 * @property integer $store_id
 * @property integer $manager_staff_id
 * @property integer $address_id
 * @property string $last_update
 *
 * @property \app\models\SakilaCustomer[] $sakilaCustomers
 * @property \app\models\SakilaInventory[] $sakilaInventories
 * @property \app\models\SakilaStaff[] $sakilaStaff
 * @property \app\models\SakilaAddress $address
 * @property \app\models\SakilaStaff $managerStaff
 * @property string $aliasModel
 */
abstract class SakilaStore extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sakila_store';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['manager_staff_id', 'address_id'], 'required'],
            [['manager_staff_id', 'address_id'], 'integer'],
            [['last_update'], 'safe'],
            [['manager_staff_id'], 'unique'],
            [['address_id'], 'exist', 'skipOnError' => true, 'targetClass' => SakilaAddress::className(), 'targetAttribute' => ['address_id' => 'address_id']],
            [['manager_staff_id'], 'exist', 'skipOnError' => true, 'targetClass' => SakilaStaff::className(), 'targetAttribute' => ['manager_staff_id' => 'staff_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'store_id' => Yii::t('app', 'Store ID'),
            'manager_staff_id' => Yii::t('app', 'Manager Staff ID'),
            'address_id' => Yii::t('app', 'Address ID'),
            'last_update' => Yii::t('app', 'Last Update'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSakilaCustomers()
    {
        return $this->hasMany(\app\models\SakilaCustomer::className(), ['store_id' => 'store_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSakilaInventories()
    {
        return $this->hasMany(\app\models\SakilaInventory::className(), ['store_id' => 'store_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSakilaStaff()
    {
        return $this->hasMany(\app\models\SakilaStaff::className(), ['store_id' => 'store_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAddress()
    {
        return $this->hasOne(\app\models\SakilaAddress::className(), ['address_id' => 'address_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getManagerStaff()
    {
        return $this->hasOne(\app\models\SakilaStaff::className(), ['staff_id' => 'manager_staff_id']);
    }


    
    /**
     * @inheritdoc
     * @return SakilaStoreQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\SakilaStoreQuery(get_called_class());
    }


}
