<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "sakila_film_category".
 *
 * @property integer $film_id
 * @property integer $category_id
 * @property string $last_update
 *
 * @property \app\models\SakilaCategory $category
 * @property \app\models\SakilaFilm $film
 * @property string $aliasModel
 */
abstract class SakilaFilmCategory extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sakila_film_category';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['film_id', 'category_id'], 'required'],
            [['film_id', 'category_id'], 'integer'],
            [['last_update'], 'safe'],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => SakilaCategory::className(), 'targetAttribute' => ['category_id' => 'category_id']],
            [['film_id'], 'exist', 'skipOnError' => true, 'targetClass' => SakilaFilm::className(), 'targetAttribute' => ['film_id' => 'film_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'film_id' => Yii::t('app', 'Film ID'),
            'category_id' => Yii::t('app', 'Category ID'),
            'last_update' => Yii::t('app', 'Last Update'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(\app\models\SakilaCategory::className(), ['category_id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFilm()
    {
        return $this->hasOne(\app\models\SakilaFilm::className(), ['film_id' => 'film_id']);
    }


    
    /**
     * @inheritdoc
     * @return SakilaFilmCategoryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\SakilaFilmCategoryQuery(get_called_class());
    }


}
