<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "sakila_film_text".
 *
 * @property integer $film_id
 * @property string $title
 * @property string $description
 * @property string $aliasModel
 */
abstract class SakilaFilmText extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sakila_film_text';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['film_id', 'title'], 'required'],
            [['film_id'], 'integer'],
            [['description'], 'string'],
            [['title'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'film_id' => Yii::t('app', 'Film ID'),
            'title' => Yii::t('app', 'Title'),
            'description' => Yii::t('app', 'Description'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return SakilaFilmTextQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\SakilaFilmTextQuery(get_called_class());
    }


}
