<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "sakila_address".
 *
 * @property integer $address_id
 * @property string $address
 * @property string $address2
 * @property string $district
 * @property integer $city_id
 * @property string $postal_code
 * @property string $phone
 * @property string $last_update
 *
 * @property \app\models\SakilaCity $city
 * @property \app\models\SakilaCustomer[] $sakilaCustomers
 * @property \app\models\SakilaStaff[] $sakilaStaff
 * @property \app\models\SakilaStore[] $sakilaStores
 * @property string $aliasModel
 */
abstract class SakilaAddress extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sakila_address';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['address', 'district', 'city_id', 'phone'], 'required'],
            [['city_id'], 'integer'],
            [['last_update'], 'safe'],
            [['address', 'address2'], 'string', 'max' => 50],
            [['district', 'phone'], 'string', 'max' => 20],
            [['postal_code'], 'string', 'max' => 10],
            [['city_id'], 'exist', 'skipOnError' => true, 'targetClass' => SakilaCity::className(), 'targetAttribute' => ['city_id' => 'city_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'address_id' => Yii::t('app', 'Address ID'),
            'address' => Yii::t('app', 'Address'),
            'address2' => Yii::t('app', 'Address2'),
            'district' => Yii::t('app', 'District'),
            'city_id' => Yii::t('app', 'City ID'),
            'postal_code' => Yii::t('app', 'Postal Code'),
            'phone' => Yii::t('app', 'Phone'),
            'last_update' => Yii::t('app', 'Last Update'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCity()
    {
        return $this->hasOne(\app\models\SakilaCity::className(), ['city_id' => 'city_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSakilaCustomers()
    {
        return $this->hasMany(\app\models\SakilaCustomer::className(), ['address_id' => 'address_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSakilaStaff()
    {
        return $this->hasMany(\app\models\SakilaStaff::className(), ['address_id' => 'address_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSakilaStores()
    {
        return $this->hasMany(\app\models\SakilaStore::className(), ['address_id' => 'address_id']);
    }


    
    /**
     * @inheritdoc
     * @return SakilaAddressQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\SakilaAddressQuery(get_called_class());
    }


}
