<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "sakila_category".
 *
 * @property integer $category_id
 * @property string $name
 * @property string $last_update
 *
 * @property \app\models\SakilaFilmCategory[] $sakilaFilmCategories
 * @property \app\models\SakilaFilm[] $films
 * @property string $aliasModel
 */
abstract class SakilaCategory extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sakila_category';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['last_update'], 'safe'],
            [['name'], 'string', 'max' => 25]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'category_id' => Yii::t('app', 'Category ID'),
            'name' => Yii::t('app', 'Name'),
            'last_update' => Yii::t('app', 'Last Update'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSakilaFilmCategories()
    {
        return $this->hasMany(\app\models\SakilaFilmCategory::className(), ['category_id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFilms()
    {
        return $this->hasMany(\app\models\SakilaFilm::className(), ['film_id' => 'film_id'])->viaTable('sakila_film_category', ['category_id' => 'category_id']);
    }


    
    /**
     * @inheritdoc
     * @return SakilaCategoryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\SakilaCategoryQuery(get_called_class());
    }


}
