<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var app\models\SakilaFilm $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="sakila-film-form">

    <?php $form = ActiveForm::begin([
    'id' => 'SakilaFilm',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            
			<?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>
			<?= $form->field($model, 'release_year')->textInput(['maxlength' => true]) ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'language_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\SakilaLanguage::find()->all(), 'language_id', 'name'),
    ['prompt' => Yii::t('cruds', 'Select')]
); ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'original_language_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\SakilaLanguage::find()->all(), 'language_id', 'name'),
    ['prompt' => Yii::t('cruds', 'Select')]
); ?>
			<?= $form->field($model, 'rental_duration')->textInput() ?>
			<?= $form->field($model, 'rental_rate')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'length')->textInput() ?>
			<?= $form->field($model, 'replacement_cost')->textInput(['maxlength' => true]) ?>
			<?=                         $form->field($model, 'rating')->dropDownList(
                            app\models\SakilaFilm::optsrating()
                        ); ?>
			<?= $form->field($model, 'special_features')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'last_update')->textInput() ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                   'encodeLabels' => false,
                     'items' => [ [
    'label'   => Yii::t('models', StringHelper::basename('app\models\SakilaFilm')),
    'content' => $this->blocks['main'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('cruds', 'Create') : Yii::t('cruds', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

